[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1"
calamine = {path = "../../external/calamine"}
pdf = { path = "../../external/pdf-rs/pdf" }
memchr = "2"
reqwest = { version = "0.12", features = ["json"] } # Or the latest version
tokio = { version = "1", features = ["full"] }    # Or specify features as needed
chrono = "0.4.45"
